import "./globals.css";
import { AuthProvider } from "@/context";
import { Navbar } from '../components/Navbar'
import { BillsProvider } from "@/context/BillsContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-white container mx-auto">
        <AuthProvider>
          <BillsProvider>
            <nav>
              <Navbar />
            </nav>
            <main>
              {children}
            </main>
            <footer></footer>
          </BillsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
